services:

  db:
    image: postgres:17-alpine
    container_name: smartagent_db
    restart: always
    env_file:
      - ./backend/.env.confdb
    volumes:
      - smartagent_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartagent_backend
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8001"
    restart: always
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartagent_frontend
    expose:
      - "80"
    ports:
      - "8080:80"
    depends_on:
      - smartagent_backend
    networks:
      - app_network

volumes:
  smartagent_pgdata:

networks:
  app_network:
    external: true