server {
    listen 80;
    server_name smartaudit.goevolux.com.br;

    resolver 127.0.0.11 valid=10s;

    location /api/v1/ {
        set $upstream http://smart_audit_backend:8003;
        proxy_pass $upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /uploads/ {
        set $upstream http://smart_audit_backend:8003;
        proxy_pass $upstream;
    }

    location /app/ {
        set $upstream http://smart_audit_frontend:80;
        proxy_pass $upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location / {
        set $upstream http://smart_audit_frontend:80;
        proxy_pass $upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}