"""add token and amount_usdc to strategy and execution

Revision ID: 59122cf0c1c4
Revises: 133080499b46
Create Date: 2026-05-10 16:59:34.936107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59122cf0c1c4'
down_revision: Union[str, Sequence[str], None] = '133080499b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('token', sa.String(length=10), nullable=False, server_default='SOL'))
    op.add_column('executions', sa.Column('amount_usdc', sa.Float(), nullable=True))
    op.add_column('strategies', sa.Column('token', sa.String(length=10), nullable=False, server_default='SOL'))
    op.add_column('strategies', sa.Column('amount_usdc', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'amount_usdc')
    op.drop_column('strategies', 'token')
    op.drop_column('executions', 'amount_usdc')
    op.drop_column('executions', 'token')
    # ### end Alembic commands ###
