"""criar campos em strategy last_executed_at, cooldown_seconds e execution_mode.

Revision ID: 5e99293e3f4d
Revises: e99e65df20cf
Create Date: 2026-05-03 13:44:12.634534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e99293e3f4d'
down_revision: Union[str, Sequence[str], None] = 'e99e65df20cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('last_executed_at', sa.DateTime(), nullable=True))
    op.add_column('strategies', sa.Column('cooldown_seconds', sa.Integer(), nullable=False))
    op.add_column('strategies', sa.Column('execution_mode', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'execution_mode')
    op.drop_column('strategies', 'cooldown_seconds')
    op.drop_column('strategies', 'last_executed_at')
    # ### end Alembic commands ###
