"""add_sessions_table

Revision ID: 6e84c397014c
Revises: a8f3d2e91c05
Create Date: 2026-05-20 00:06:51.479516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e84c397014c'
down_revision: Union[str, Sequence[str], None] = 'a8f3d2e91c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delegate_pubkey', sa.String(length=255), nullable=False),
    sa.Column('encrypted_private_key', sa.String(length=512), nullable=False),
    sa.Column('session_token_address', sa.String(length=255), nullable=False),
    sa.Column('spending_limit', sa.BigInteger(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
