"""Tabela execution 2

Revision ID: 9cabf1f09990
Revises: 93a5129a0c15
Create Date: 2026-05-01 11:31:58.300854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cabf1f09990'
down_revision: Union[str, Sequence[str], None] = '93a5129a0c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('trigger_price', sa.Float(), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=False),
    sa.Column('drop_percent', sa.Float(), nullable=False),
    sa.Column('amount_sol', sa.Float(), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executions')
    # ### end Alembic commands ###
