"""Refactory in tables (user, wallet, strategy e execution).

Revision ID: dc75c34d84fb
Revises: 9cabf1f09990
Create Date: 2026-05-02 13:44:13.896279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc75c34d84fb'
down_revision: Union[str, Sequence[str], None] = '9cabf1f09990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('wallet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'executions', 'strategies', ['strategy_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'executions', 'wallets', ['wallet_id'], ['id'], ondelete='CASCADE')
    op.add_column('strategies', sa.Column('wallet_id', sa.Integer(), nullable=False))
    op.add_column('strategies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'strategies', 'wallets', ['wallet_id'], ['id'], ondelete='CASCADE')
    op.drop_column('strategies', 'user_id')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('wallets', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'wallets', ['public_key'])
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('wallets', 'encrypted_private_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('encrypted_private_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_constraint(None, 'wallets', type_='unique')
    op.drop_column('wallets', 'created_at')
    op.drop_column('users', 'created_at')
    op.add_column('strategies', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_column('strategies', 'created_at')
    op.drop_column('strategies', 'wallet_id')
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.drop_column('executions', 'wallet_id')
    # ### end Alembic commands ###
