"""criar external_id tabela execution.

Revision ID: e99e65df20cf
Revises: c1ebdbede1ba
Create Date: 2026-05-03 00:09:52.092833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99e65df20cf'
down_revision: Union[str, Sequence[str], None] = 'c1ebdbede1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'executions', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'executions', type_='unique')
    op.drop_column('executions', 'external_id')
    # ### end Alembic commands ###
